### PR TITLE
test: replace deprecated getTranslation calls

### PR DESCRIPTION
**Pull request by mcollovati**

### CODE REVIEW

**Comment by caalador** [comment]
Looks strange that the `getTranslation(String key, Locale locale, Object... params)` which is deprecated is actually the one used from `getTranslation(Locale locale, String key, Object... params)`... It would perhaps make more sense if the deprecated one would call the "actual" method and not the other way around.
Also as it was introduced in 22.0 when should the deprecated method be removed?

**Comment by mcollovati** [comment]
Good point! Looks like we forgot to remove them in 24.0.
So, I suppose we should clean up in 25.
But it would probably make sense to swap the implementation code on Flow right now

**Comment by mcollovati** [comment]
And the change actually makes the test fail because `getTranslation(new Locale("fi", "FI", "label"))` calls `getTranslation(Object key, Object... params)`

**Comment by mcollovati** [comment]
Also, `I18NProvider` methods have the `Locale` as a second parameter. It looks like a bit confusing :thinking:

**Review by caalador — APPROVED** [review]

**Pull request merged**
