### PR TITLE
fix: use quarkus integration tests and generate screenshots on failure

### LINKED ISSUE #23: IT tests are lacking snapshots on failure

### PR DESCRIPTION
**Pull request by denis-anisimov**
Quarkus integration tests should be used instead of unit tests.
Screenshot on failure extension is added.

fixes #23

## Description

Please list all relevant dependencies in this section and provide summary of the change, motivation and context.

Fixes # (issue)

## Type of change

- [x] Bugfix
- [ ] Feature

## Checklist

- [ ] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [ ] I have added a description following the guideline.
- [ ] The issue is created in the corresponding repository and I have referenced it.
- [ ] I have added tests to ensure my change is effective and works as intended.
- [ ] New and existing tests are passing locally with my change.
- [ ] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

### CODE REVIEW

**Review by caalador — APPROVED** [review]
For some reason the build fails with:
```
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: io/quarkus/bootstrap/runner/QuarkusEntryPoint has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
```
Which would indicate that something is trying to execute using jdk8 when jdk11 should be used

**Comment by denis-anisimov** [comment]
> 
> Which would indicate that something is trying to execute using jdk8 when jdk11 should be used

yes, and I have no idea what

**Comment by denis-anisimov** [comment]
This PR is failing because of bug in Quarkus plugin :https://github.com/quarkusio/quarkus/issues/20049.

Let's don't close this and wait when the fix (which is already provided) will be included in the release.
Once it's released the PR van be revalidated and merged.
Nothing else can be done at this moment.

**Comment by mshabarov** [comment]
@denis-anisimov the ticket is closed with `2.3.0.CR1` milestone, so maybe the new version is already available.

**Comment by caalador** [comment]
Seems ok and by the one failing run seems to work as expected, but there is some issue with the rebase as the PR seems to show a bunch of changes that are not from this fix.

**Comment by denis-anisimov** [comment]
Closed in favor of https://github.com/vaadin/quarkus/pull/39

**Pull request closed without merging**
