### PR TITLE
fix: use quarkus compatible classloader

### PR DESCRIPTION
**Pull request by caalador**
Use a classLoader that is
compatible with quarkus for
default i18N translation.

part of vaadin/flow#18977

### CODE REVIEW

**Comment by caalador** [comment]
Depends on vaadin/flow#19136
Also proposes update add-on from 2.0 to 2.1 meaning that 2.0 should be branched out from main branch.

**Comment by mcollovati** [comment]
> Also proposes update add-on from 2.0 to 2.1 meaning that 2.0 should be branched out from main branch.

Is it reasonable to have two separated commits for version bump and the instantiator change and then do a `rebase and merge` instead of squash?

**Comment by mcollovati** [comment]
A minor nit: swapping the order of the commits would make both of them compilable once we have the new Flow snapshot. With the current order (first code changes than Flow bump) the first commit will be broken.

**Comment by caalador** [comment]
Now the test is there and the assertions should be build in the correct order.

**Comment by mcollovati** [comment]
Was already picked manually

**Pull request merged**
